### ISSUE TITLE
Should add `requires_grad=False` to `new_val`

### ISSUE THREAD

**Issue by TabuaTambalam** [FrancescoSaverioZuppichini/Loading-huge-PyTorch-models-with-linear-memory-consumption#1]
In the line of `new_val = torch.nn.Parameter(val, requires_grad=False)`
Wasted 1 hour of google colab gpu time and found this fix.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @TabuaTambalam , sorry to hear about your bad luck with colab :( In theory, calling the model inside a `torch.no_grad` should do the same thing, right?

**Comment by TabuaTambalam** [comment]
I also didn't notice this issue because I always use `load_state_dict_with_low_memory()` with `torch.set_grad_enabled(False)` or `model.requires_grad_(False)`.
Until today I'm going to do some training/fitting tasks, and can't just global-ly turn grad off like that.

It's better to turn off per-tensor grad by default, seems original `load_state_dict()` did that too.

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks, done it :)
